### ISSUE TITLE
Suggestion: Allow Independent setting of Gear Stats from hardness value.

### ISSUE THREAD

**Issue by TeetoKaziim** [RoMiMoCo/Ores#15]
I have a suggestion, that arose when I tried and failed to make a material with stats equivalent to just above diamond. What I ended up with, was a sword that was weaker than diamond, and armor that was stronger than diamond.

So what I'm suggesting is, optional arguments in the oreDefinitions.json, that when supplied, get used in place of "hardness" for determining specific stats. And to maintain back compatibility, if they're not supplied, you can just have it generate these values using the hardness entry as it does now.

"Durability"
"Damage"
"Miningspeed"
"Armor"

That all being said, thanks a bunch, this mod packs a lot of power for how simple to use it is. Greatly appreciated.

**Comment by RoMiMoCo** [comment]
So, what I think you ran into was something I added with a large amount of argument from myself.  Currently, the Hardness value is capped at the value that should approximate diamond (meaning it's impossible to create an ore harder than diamond).  I may go back and remove that, as I wasn't fully convinced it was a good idea to add it in the first place.

Currently, Hardness is translated to durability, damage, etc via a hastily created math function that mostly approximates vanilla.  It's hard to 100% match vanilla because the vanilla values are pretty much arbitrary.

**Comment by RoMiMoCo** [comment]
Fixed in 0.4.0
